### PR TITLE
Hotfix link image

### PR DESCRIPTION
**Pull request by mrvladnov**

### CODE REVIEW

**Comment by mrvladnov** [comment]
excellent PR, merged

**Comment by markprokoudine** [comment]
excellent PR!

**Comment by Cohedrin** [comment]
excellent PR!

**Comment by tikijian** [comment]
excellent PR!

**Comment by AlexBlom** [comment]
Just discovered this. Great PR.

**Comment by jshamash** [comment]
+1, what a PR!

**Comment by jordanyee** [comment]
Excellent PR!

**Comment by anulman** [comment]
wow! this pr!!!

**Comment by raksonibs** [comment]
Fantastic PR. Timeless.

**Pull request merged**
